### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-grok#9] opened 2015-01-30 22:24 UTC
From https://github.com/elasticsearch/logstash/issues/2487

```
  39) LogStash::Filters::Grok break_on_match = true (default) for array input with multiple grok pattern "{"message":["hello world","line 23"]}" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "hello", but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  40) LogStash::Filters::Grok singles with duplicate-named fields "hello world" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       NilClass is not a String
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  41) LogStash::Filters::Grok empty fields drop by default "1=test" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected nil, got ["_grokparsefailure"]
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  42) LogStash::Filters::Grok empty fields keep if keep_empty_captures is true "1=test" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected nil, got ["_grokparsefailure"]
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  43) LogStash::Filters::Grok processing selected fields "{"message":"hello world","examplefield":"12345"}" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "hello", but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  44) LogStash::Filters::Grok allow dashes in capture names "hello world" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "hello", but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  45) LogStash::Filters::Grok when named_captures_only == false "Hello World, yo!" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "WORD" in #<LogStash::Event:0x123c8f2 @metadata={}, @accessors=#<LogStash::Util::Accessors:0x5da00b @store={"message"=>"Hello World, yo!", "@version"=>"1", "@timestamp"=>"2015-01-30T22:12:55.202Z", "tags"=>["_grokparsefailure"]}, @lut={"message"=>[{"message"=>"Hello World, yo!", "@version"=>"1", "@timestamp"=>"2015-01-30T22:12:55.202Z", "tags"=>["_grokparsefailure"]}, "message"], "tags"=>[{"message"=>"Hello World, yo!", "@version"=>"1", "@timestamp"=>"2015-01-30T22:12:55.202Z", "tags"=>["_grokparsefailure"]}, "tags"], "WORD"=>[{"message"=>"Hello World, yo!", "@version"=>"1", "@timestamp"=>"2015-01-30T22:12:55.202Z", "tags"=>["_grokparsefailure"]}, "WORD"]}>, @logger=#<Cabin::Channel:0x16169da @subscriber_lock=#<Mutex:0x6ca36a>, @data={}, @metrics=#<Cabin::Metrics:0x5cac5f @channel=#<Cabin::Channel:0x16169da ...>, @metrics={}, @metrics_lock=#<Mutex:0x38b0f5>>, @subscribers={}, @level=:info>, @data={"message"=>"Hello World, yo!", "@version"=>"1", "@timestamp"=>"2015-01-30T22:12:55.202Z", "tags"=>["_grokparsefailure"]}, @metadata_accessors=#<LogStash::Util::Accessors:0xc46d2 @store={}, @lut={}>, @cancelled=false>
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  46) LogStash::Filters::Grok patterns in custom dir override those in 'patterns/' dir "{"message":"0"}" when processed
     Failure/Error: Unable to find matching line from backtrace
     Errno::EACCES:
       Permission denied - C:/Users/jls/AppData/Local/Temp/d20150130-1484-3g3zk8/grok20150130-1484-14bwd5b
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  47) LogStash::Filters::Grok break_on_match = false for array input with multiple grok pattern "{"message":["hello world 123","line 23"]}" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected ["hello", "line"], but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  48) LogStash::Filters::Grok break_on_match = false for array input with multiple grok pattern "{"message":["hello world","line 23"]}" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected ["hello", "line"], but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

```

**Comment by wiibaa** [comment] 2015-02-02 05:47
Investigating the cases [41 and 42](https://github.com/logstash-plugins/logstash-filter-grok/blob/master/spec/filters/grok_spec.rb#L249-L287)
For me, on Windows, the WORD definition was overriden by a pattern file in the logstash gem 
`jruby-1.7.17\lib\ruby\gems\shared\bundler\gems\logstash-2331739bb57e\patterns`
as seen in the debug log
````
←[32mAdding pattern {"WORD"=>"\\b[2-5]\\b", :level=>:info, :file=>"/dev/tools/jruby-1.7.17/lib/ruby/gems/shared/gems/jls-grok-0.11.0/lib/grok-pure.rb", :line=>"62", :method=>"add_pattern"}←[0m
````
This file remains around because test creating it is failing too, see 46).
https://github.com/logstash-plugins/logstash-filter-grok/blob/master/spec/filters/grok_spec.rb#L671-L696
Any idea how to enforce the cleanup in rspec and reduce such side-effect?

**Comment by wiibaa** [comment] 2015-02-02 06:03
In fact after removing the two last tests implying tempfiles and cleaning the pattern dirs in the gem, the full spec is reliably OK. So it is more an issue about running the spec on windows than a bug in grok itself.

**Comment by ph** [comment] 2015-02-03 15:40
@wiibaa thx for the investigation. :+1:  :)

**Comment by ph** [comment] 2015-02-03 18:35
Fixed in:
https://github.com/jordansissel/ruby-grok/pull/16
https://github.com/logstash-plugins/logstash-filter-grok/pull/10

**Comment by jsvd** [comment] 2015-02-05 12:21
In my windows box I edited the installed grok-pure lib to ensure closing the file and then pulled pr/10 but I still get 9 failures: https://gist.github.com/jsvd/084f7fcd27508797923b

did I miss some other patch?

**Comment by ph** [comment] 2015-02-09 16:18
@jsvd you should have all the patch for this bug? I suggest you remove the gems reinstall them and use the patch. I think you may have some left over files, when the tests had side effects.

**Comment by jsvd** [comment] 2015-02-10 14:03
I still get this issue after cloning logstash master, applying this PR and the ruby-grok patch manually.
https://gist.github.com/jsvd/51a8111a7d6ba3365868

**Comment by jsvd** [comment] 2015-02-10 14:43
Confirmed that manually deleting patterns in the `patterns\` dir, applying the ruby-grok patch and this patch makes the tests pass inside logstash.
Maybe the test files should be generated in a temporary directory instead of `patterns\`?
Otherwise LGTM

**Comment by ph** [comment] 2015-02-10 14:46
This is more like an integration test to make sure we can override the pattern in the pattern dir, the other files are generated in a tmp folder. 

IMHO, We should revisit all the test suite of the grok filter to refactor them and to use `Stud::Temporary`

**Closed** 2015-02-10 19:28 UTC
