### ISSUE TITLE
Add timeout option to grok filter

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-filter-grok#65] opened 2015-12-10 20:47 UTC
We have users sending in occasional large messages of many Mbs, and if they have not implemented logic in the pipeline to filter out these messages, the grok filter will run and peg the CPU threads for a very long time.  It will be helpful to have a default (or configurable) timeout for grok filters so that it will give up at some point, etc..

**Comment by jordansissel** [comment] 2015-12-10 20:55
We used to have a watchdog that caught runaway filters in these situations.
We can bring it back - good idea :)

**Comment by jordansissel** [comment] 2016-01-20 09:10
Related: Joni (as of 2.5-ish years ago) supports being interrupted [via Thread.interrupt](https://github.com/jruby/joni/commit/1822b0f30e0e85071183f1e7a082f5476a437294).

**Comment by jordansissel** [comment] 2016-01-20 09:14
Proposal for this:

1) Configurable execution timeout. Default 0.5 seconds.
2) When execution time expires, we interrupt grok via java Thread.interrupt().
3) On interruption, we tag the event _grokexecutiontimeout and continue on to the next filter in the filter worker.

This may get tricky given the new complexity of the combined filter-and-output worker units as well as having some possibility (we'll need to protect against) of race conditions of grok succeeding vs the timer expiring.

**Comment by purbon** [comment] 2016-01-20 11:55
I think your last comment will have a very nice improvement for grok, specially when problematic situation happen.

+1 for them.

**Comment by charlieflowers** [comment] 2016-04-19 16:47
I wonder if this issue was accidentally closed? This issue is referenced by #4699, but it is closed also. It appears there is no open issue which tracks this?

We're very interested in the issue and are trying to track it. Is there another issue that tracks it now?

**Comment by wiibaa** [comment] 2016-05-27 06:49
@suyograo can we close this as duplicate of #82 ?

**Comment by magicdude4eva** [comment] 2016-11-08 13:05
Perhaps related - I have no idea why a simple regex times out - https://github.com/logstash-plugins/logstash-filter-grok/issues/99

**Comment by jsvd** [comment] 2017-12-29 10:50
this was implemented in https://github.com/logstash-plugins/logstash-filter-grok/pull/88

**Closed by jsvd** 2017-12-29 10:50 UTC
Labels: enhancement, resiliency
